/**
 * Generates a full `named.conf.local` listing zone blocks. Rewritten from DB on each apply.
 */
export const generateNamedConfLocal = (
	zones: Array<{ fileName: string; zoneName: string }>,
): string => {
	const blocks = zones.map(
		(z) => `zone "${z.zoneName}" {\n\ttype master;\n\tfile "${z.fileName}";\n};`,
	)
	return `// Generated by Dokploy panel — do not hand-edit\n${blocks.join("\n\n")}\n`
}
